### ISSUE TITLE
Error with create-react-app

### ISSUE THREAD

**Issue by getflixFaisal** [personality-insights/trait-info#3]
Hello Admin (@germanattanasio, @aprilwebster ),
Related to issue in trait-description : [this](https://github.com/personality-insights/trait-descriptions/issues/3)

Can team please do the same thing here too? because I think trait-info contains all other train-bla bla package, and it will be useful if this package being updated.

I have school project using this library and got frustating because error when build with create-react-app

Thank you

**Comment by germanattanasio** [comment]
We can totally do it!

**Comment by germanattanasio** [comment]
Well, what if you to do it and create a Pull Request? You can be part of our contributors.

We send Christmas cards to our Github contributors

**Comment by germanattanasio** [comment]
We don't actually send cards 😝

**Comment by germanattanasio** [comment]
This should be working now @getflixFaisal.

**Comment by getflixFaisal** [comment]
@germanattanasio Hi, sorry for late response. I just revisited my code and I think its still not woriking.
Here is the log from my output when tried to build using: "npm run build".
I already updated personality-trait-info to version 3.0.4

> Creating an optimized production build...
> Failed to compile.
> 
> static/js/main.76639d80.js from UglifyJs
> SyntaxError: Unexpected token: name (I18nData) [./~/personality-trait-names/lib/i18n/v2/index.js:27,0]
> 
> 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
> npm ERR! node v6.10.2
> npm ERR! npm  v3.10.10
> npm ERR! code ELIFECYCLE
> npm ERR! test@0.1.0 build: `react-scripts build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the test@0.1.0 build script 'react-scripts build'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the test package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     react-scripts build
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs test
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls test
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\ots-frontend\npm-debug.log
